### ISSUE TITLE
Unable to get it working, error whenever I use it

### ISSUE THREAD

**Issue by messycoding** [feathersjs-offline/owndata-ownnet#43]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs-offline/owndata-ownnet/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behaviour
There is should be no error when using

```
import { Owndata } from '@feathersjs-offline/client';
Owndata(app, '/messages', {});
```

### Actual behaviour
The app crash and the error is this.

<img width="567" alt="Screen Shot 2021-07-15 at 2 43 52 PM" src="https://user-images.githubusercontent.com/87465548/125741655-c09aa5ab-1c73-4459-b93d-587bd39d6f4a.png">

This error shows whenever I call.
`Owndata(app, '/messages', {});`

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
"@feathersjs-offline/client": "1.0.7"

**NodeJS version**:
v14.16.0

**Operating System**:
macbook catalina 10.15.7

**Browser Version**:

**React Native Version**:
"react-native": "0.64.2"

**Module Loader**:

**Comment by mhillerstrom** [comment]
Please try to use either `owndataWrapper` or `ownnetWrapper` as per the documentation https://feathersjs-offline.github.io/docs/guides/basics/offline-first.html#come-on-it-can-t-be-that-simple

**Comment by messycoding** [comment]
Yes, that is the guide I followed. I installed @feathersjs-offline/client then I import it

`import { owndataWrapper } from '@feathersjs-offline/client';`

then moment I call

`owndataWrapper(app, '/messages', {});`

the app crash and the error shows up.

**Comment by messycoding** [comment]
here is the screenshot using owndataWrapper
<img width="1062" alt="Screen Shot 2021-07-16 at 12 25 52 PM" src="https://user-images.githubusercontent.com/87465548/125891704-c2f0767a-5728-450b-8799-7d4ffe9b19cd.png">

**Comment by messycoding** [comment]
Here is the screenshot using owndataWrapper

![proof](https://user-images.githubusercontent.com/87465548/125891976-e955ba01-d634-4b48-a32e-3ca310324c2d.jpg)

**Comment by mhillerstrom** [comment]
Well, I'm pretty sure it works, but I can see, that the last example `owndataWrapper` will not work, unless you uncomment the `app.use('/messages', ...)` as the wrappers presupposes the service to be setup. I'm most likely to suggest you try the action points suggested by the error:
1. clear ..
2. Delete
3. Reset ...
4. Remove ...

Otherwise, I need access to more of your code in order to be able to give qualified help.

**Comment by messycoding** [comment]
Hi, thank you so much for the response, this is the code

https://github.com/messycoding/myfeathersofflinefirstproject

**Comment by messycoding** [comment]
I tried several times doing these steps:

1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
 
 Still, I get the same error about local storage
 
```
 error: Error: Unable to resolve module path from ~/Documents/TESTING/REACT_NATIVE/featherofflinefirstwrapper/node_modules/node-localstorage/LocalStorage.js: path could not be found within the project or in these directories:
  node_modules
```

Even though I already installed node-localstorage and checked the node_modules and it is there.

<img width="227" alt="Screen Shot 2021-07-20 at 7 28 13 AM" src="https://user-images.githubusercontent.com/87465548/126240050-79a5985d-f3de-4e32-94d3-0bfee0ebc0b6.png">

**Comment by wnxhaja** [comment]
Is it possible to reopen this one? I have the same issue. I even explicity add what storage to use.

[
![offline-first](https://user-images.githubusercontent.com/4872417/126607436-7350d483-2e10-4c89-8b99-e4753147ae9c.png)
](url)

**Comment by mhillerstrom** [comment]
Hi Abdul,

 

Did you try with version 1.0.8?

 

Regards,

Michael

 

From: Abdul Jalil Laguindab ***@***.***>
Reply-To: feathersjs-offline/owndata-ownnet ***@***.***>
Date: Thursday, 22 July 2021 at 10.05
To: feathersjs-offline/owndata-ownnet ***@***.***>
Cc: Michael Hillerström ***@***.***>, State change ***@***.***>
Subject: Re: [feathersjs-offline/owndata-ownnet] Unable to get it working,error whenever I use it (#43)

 

Is it possible to reopen this one? I have the same issue. I even explicity add what storage to use.

**Comment by wnxhaja** [comment]
Hello Michael,

Yes, I did use the latest one https://github.com/wnxhaja/rnFeathersOffline/blob/master/package.json#L13.

I think the one causing the issue is this line https://github.com/feathersjs-offline/owndata-ownnet/blob/main/packages/client/src/own-common/own-class.js#L81. Does that mean that on react-native the condition in line https://github.com/feathersjs-offline/owndata-ownnet/blob/main/packages/client/src/own-common/own-class.js#L79 will always be true?

**Comment by mhillerstrom** [comment]
I’m not a React geek by any means… So, in essence this is a problem related to “assembling” the client outside the browser? Have you come across this problem in other situations? If so, what was your resolution?

/Michael

 

From: Abdul Jalil Laguindab ***@***.***>
Reply-To: feathersjs-offline/owndata-ownnet ***@***.***>
Date: Thursday, 29 July 2021 at 04.03
To: feathersjs-offline/owndata-ownnet ***@***.***>
Cc: Michael Hillerström ***@***.***>, State change ***@***.***>
Subject: Re: [feathersjs-offline/owndata-ownnet] Unable to get it working,error whenever I use it (#43)

 

Hello Michael,

Yes, I did use the latest one https://github.com/wnxhaja/rnFeathersOffline/blob/master/package.json#L13.

I think the one causing the issue is this line https://github.com/feathersjs-offline/owndata-ownnet/blob/main/packages/client/src/own-common/own-class.js#L81. Does that mean that on react-native the condition in line https://github.com/feathersjs-offline/owndata-ownnet/blob/main/packages/client/src/own-common/own-class.js#L79 will always be true?

**Comment by wnxhaja** [comment]
Yes, the issue is during the build in react-native. I've tried two things.

First I commented out the conditional logic https://github.com/feathersjs-offline/owndata-ownnet/blob/main/packages/client/src/own-common/own-class.js#L79 and it builds successfully. Which tells me it is really the one causing the error.

Second I put it back but this time I made sure the condition will always be false so this line https://github.com/feathersjs-offline/owndata-ownnet/blob/main/packages/client/src/own-common/own-class.js#L81 will never run. But then, to my surprise, it throws an error. This means that it will never run in react-native.

Now, my question is, do we really need the conditional on line 79? Because I notice below on [line 107](https://github.com/feathersjs-offline/owndata-ownnet/blob/main/packages/client/src/own-common/own-class.js#L107) there is another condition saying if you provide a localstorage we will use it else use the default localStorage(I assume this is for browser), Isn't this enough? I think it is safe to say that if there is no default localStorage you need to provide one or it will cause an error.

**Comment by mhillerstrom** [comment]
Ok, thanks. I have made a new (breaking) version avoiding the automatic inclusion of localStorage.

 

Please let me know how it goes!

 

/Michael

 

From: Abdul Jalil Laguindab ***@***.***>
Reply-To: feathersjs-offline/owndata-ownnet ***@***.***>
Date: Friday, 30 July 2021 at 02.39
To: feathersjs-offline/owndata-ownnet ***@***.***>
Cc: Michael Hillerström ***@***.***>, State change ***@***.***>
Subject: Re: [feathersjs-offline/owndata-ownnet] Unable to get it working,error whenever I use it (#43)

 

Yes, the issue is during the build in react-native. I've tried two things.

First I commented out the conditional logic https://github.com/feathersjs-offline/owndata-ownnet/blob/main/packages/client/src/own-common/own-class.js#L79 and it builds successfully. Which tells me it is really the one causing the error.

Second I put it back but this time I made sure the condition will always be false so this line https://github.com/feathersjs-offline/owndata-ownnet/blob/main/packages/client/src/own-common/own-class.js#L81 will never run. But then, to my surprise, it throws an error. This means that it will never run in react-native.

Now, my question is, do we really need the conditional on line 79? Because I notice below on line 107 there is another condition saying if you provide a localstorage we will use it else use the default localStorage(I assume this is for browser), Isn't this enough? I think it is safe to say that if there is no default localStorage you need to provide one or it will cause an error.

**Comment by wnxhaja** [comment]
Awesome! It now builds successfully. But I encounter a new issue, I just learned that the react-native(mobile) AsyncStorage and web localStorage methods return different types.

[AsyncStorage](https://reactnative.dev/docs/asyncstoragel) returns a promise while [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) returns a value.

Storage method call like this https://github.com/feathersjs-offline/owndata-ownnet/blob/main/packages/client/src/own-common/own-class.js#L138 will cause an error.

Do you think this is still a concern of the package? Or just say no and look for alternative storage that will return a value and not a promise?

**Comment by mhillerstrom** [comment]
Ok, I’m pretty sure it should work now. Can I ask you to verify?

 

Thanks

/Michael

 

From: Abdul Jalil Laguindab ***@***.***>
Reply-To: feathersjs-offline/owndata-ownnet ***@***.***>
Date: Friday, 30 July 2021 at 23.34
To: feathersjs-offline/owndata-ownnet ***@***.***>
Cc: Michael Hillerström ***@***.***>, State change ***@***.***>
Subject: Re: [feathersjs-offline/owndata-ownnet] Unable to get it working,error whenever I use it (#43)

 

Awesome! It now builds successfully. But I encounter a new issue, I just learned that the react-native(mobile) AsyncStorage and web localStorage methods return different types.

AsyncStorage returns a promise while localStorage returns a value.

Storage method call like this https://github.com/feathersjs-offline/owndata-ownnet/blob/main/packages/client/src/own-common/own-class.js#L138 will cause an error.

Do you think this is still a concern of the package? Or just say no and look for alternative storage that will return a value and not a promise?

**Comment by wnxhaja** [comment]
yes it works now. It will build successfuly.
